In [3]:
from tensorflow.keras.datasets import mnist
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

11493376/11490434 [==============================] - 3s 0us/step


In [4]:
train_images.shape

(60000, 28, 28)

In [5]:
train_labels

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [6]:
test_images.shape

(10000, 28, 28)

In [7]:
test_labels

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

In [8]:
from tensorflow.keras import models
from tensorflow.keras import layers

In [9]:
# the network architecture 
network = models.Sequential()
network.add(layers.Dense(512, activation='relu', input_shape=(28*28,)))
network.add(layers.Dense(10, activation='softmax'))

In [10]:
# the compilation step
network.compile(optimizer='rmsprop', loss='categorical_crossentropy', metrics=['accuracy'])

In [11]:
# Preparing the image data
# reshaping the data to match the input expected by the model
train_images = train_images.reshape((60000, 28*28))
# converting to to floating point numbers between 0 and 1 since the array was an array of numbers between 0 and 255
train_images = train_images.astype('float32') / 255

test_images = test_images.reshape((10000, 28 * 28))
test_images = test_images.astype('float32') / 255

In [12]:
# Preaparing the labels
from tensorflow.keras.utils import to_categorical

train_labels = to_categorical(train_labels)
test_labels = to_categorical(test_labels)

In [13]:
train_labels

array([[0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.]], dtype=float32)

In [14]:
# fitting the model
network.fit(train_images, train_labels, epochs=5, batch_size=128)

Epoch 1/5
469/469 [==============================] - 6s 14ms/step - loss: 0.2577 - accuracy: 0.9257
Epoch 2/5
469/469 [==============================] - 6s 13ms/step - loss: 0.1035 - accuracy: 0.9691
Epoch 3/5
469/469 [==============================] - 6s 14ms/step - loss: 0.0682 - accuracy: 0.9792
Epoch 4/5
469/469 [==============================] - 7s 14ms/step - loss: 0.0494 - accuracy: 0.9858
Epoch 5/5
469/469 [==============================] - 7s 15ms/step - loss: 0.0371 - accuracy: 0.9891


In [15]:
# printing the accuracy of the model
test_loss, test_acc = network.evaluate(test_images, test_labels)
print('Testing accuracy = ', test_acc * 100)
print('Testing loss = ', test_loss * 100)

313/313 [==============================] - 1s 3ms/step - loss: 0.0642 - accuracy: 0.9813
Testing accuracy =  98.12999963760376
Testing loss =  6.421122699975967
